apiVersion: v1
kind: Service
metadata:
  name: vuln-app-svc
  namespace: dev
spec:
  selector:
    app: vuln-app
  ports:
    - protocol: TCP
      port: 6000
      nodePort: 30007
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: vuln-app
  namespace: dev
  labels:
    app: vuln-app
spec:
  securityContext:
    fsGroup: 234
    runAsUser: 234
    runAsGroup: 234
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: vuln-app
      image: vuln_app:1.0
      ports:
        - containerPort: 6000
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
