apiVersion: v1
kind: Service
metadata:
  name: vuln-app-svc
  namespace: dev
spec:
  selector:
    app: vuln-app
  ports:
    - protocol: TCP
      port: 6000
      nodePort: 30007
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: vuln-app
  namespace: dev
  labels:
    app: vuln-app
spec:
  serviceAccountName: default
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: vuln-app
      image: vuln_app:1.0
      ports:
        - containerPort: 6000
      securityContext:
        runAsUser: 22222
        runAsGroup: 22222
        runAsNonRoot: true
        privileged: false
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "100Mi"
          cpu: "450m"
