apiVersion: v1
kind: Pod
metadata:
  name: alpine-dev
  namespace: dev
  labels:
    app: alpine-dev
spec:
  serviceAccountName: default
  securityContext:
    fsGroup: 11111
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: alpine-dev
      image: alpine:dev
      securityContext:
        runAsUser: 11111
        runAsGroup: 11111
        runAsNonRoot: true
        privileged: false
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "100Mi"
          cpu: "450m"
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: nginx-secret
        items:
          - key: tls.crt
            path: tls.crt
