apiVersion: v1
kind: Pod
metadata:
  name: alpine-dev
  namespace: dev
  labels:
    app: alpine-dev
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: alpine-dev
      image: alpine:dev
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 15342
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
          add:
            - NET_BIND_SERVICE
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret
  volumes:
    - name: secret-volume
      secret:
        secretName: nginx-secret
        items:
          - key: tls.crt
            path: tls.crt
