apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.29

    # We are setting these to our _desired_ `enforce` level.
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.29
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.29
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    name: security
