apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  # Don't generate audit events for following stages
  - "RequestReceived"
  - "ResponseStarted"
  - "Panic"
rules:
  # Log operations on Pods at RequestResponse level
  - level: RequestResponse
    verbs: ["get", "list", "create", "delete"]
    resources:
      - group: ""
        resources: ["pods"]

  # Log operations on Nodes at RequestResponse level
  - level: RequestResponse
    verbs: ["get", "list"]
    resources:
      - group: ""
        resources: ["nodes"]

  # Log operations on ConfigMaps and Secrets at the Metadata level.
  - level: Metadata
    verbs: ["get", "list", "create", "delete"]
    resources:
      - group: ""
        resources: ["secrets", "configmaps"]

  # Log operations on Namespaces at Metadata level
  - level: Metadata
    resources:
      - group: ""
        resources: ["namespaces"]

  # Log operations on Roles, RoleBindings, ClusterRoles and
  # ClusterRoleBindings at RequestResponse level
  - level: RequestResponse
    verbs: ["get", "list", "create", "delete"]
    resources:
      - group: "rbac.authorization.k8s.io"
        resources:
          ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]

  ## Not used

  # Log operations on Services at RequestResponse level
  - level: RequestResponse
    verbs: ["get", "list", "create", "delete"]
    resources:
      - group: ""
        resources: ["services"]

  # Log operations on ServiceAccounts at RequestResponse level
  - level: RequestResponse
    verbs: ["get", "list", "create", "delete"]
    resources:
      - group: ""
        resources: ["serviceaccounts"]

  # Log operations on NetworkPolicy changes at RequestResponse level
  - level: RequestResponse
    verbs: ["get", "list", "create", "delete"]
    resources:
      - group: "networking.k8s.io"
        resources: ["networkpolicies"]
    namespaces: ["dev"]

  ## DON'T WATCH RULES

  # Don't log the request body of configmap changes in kube-system.
  - level: None
    resources:
      - group: ""
        resources: ["configmaps"]
    # This rule only applies to resources in the "kube-system" namespace.
    # The empty string "" can be used to select non-namespaced resources.
    namespaces: ["kube-system"]

  # Don't log node changes
  - level: None
    resources:
      - group: ""
        resources: ["nodes"]

  # Don't log watch requests by the "system:kube-proxy" on endpoints or services
  - level: None
    users: ["system:kube-proxy"]
    verbs: ["watch"]
    resources:
      - group: ""
        resources: ["endpoints", "services"]

  # Don't log authenticated requests to certain non-resource URL paths.
  - level: None
    userGroups: ["system:authenticated"]
    nonResourceURLs:
      - "/api*" # Wildcard matching.
      - "/version"
