apiVersion: audit.k8s.io/v1 # This is required.
kind: Policy
# Don't generate audit events for all requests in RequestReceived stage.
omitStages:
  - "RequestReceived"
  - "ResponseStarted"
  - "Panic"
rules:
  # Log pod changes at RequestResponse level
  - level: RequestResponse
    verbs: ["get", "create", "update", "patch", "delete"]
    resources:
      - group: "" # core API group
        # Resource "pods" doesn't match requests to any subresource of pods (like /status or /log),
        # which is consistent with the typical RBAC policy.
        resources: ["pods"]
    namespaces: ["security", "dev"]

  # Only check access to resource "pods"
  # - level: Metadata
  #   resources:
  #     - group: ""
  #       resources: ["pods/log", "pods/status"]

  # Log configmap and secret changes at the Metadata level.
  - level: Metadata
    verbs: ["get", "create", "update", "patch", "delete"]
    resources:
      - group: ""
        resources: ["secrets", "configmaps"]
    namespaces: ["security", "dev"]

  # Log role and rolebinding changes at RequestResponse level
  - level: RequestResponse
    verbs: ["get", "create", "update", "patch", "delete"]
    resources:
      - group: "rbac.authorization.k8s.io"
        resources:
          ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    namespaces: ["security", "dev"]

  # Log serviceaccount changes at RequestResponse level
  - level: RequestResponse
    verbs: ["get", "create", "update", "patch", "delete"]
    resources:
      - group: ""
        resources: ["serviceaccounts"]
    namespaces: ["security", "dev"]

  # Log NetworkPolicy changes at RequestResponse level
  - level: RequestResponse
    verbs: ["get", "create", "update", "patch", "delete"]
    resources:
      - group: "networking.k8s.io"
        resources: ["networkpolicies"]
    namespaces: ["security", "dev"]

  # TODO: Add watching actions of user

  # # Log all actions performed by system:admin and other system users
  # - level: RequestResponse
  #   users: ["system:admin", "system:serviceaccount:kube-system:default"]

  ### DON'T WATCH RULES

  # Log the request body of configmap changes in kube-system.
  - level: None
    resources:
      - group: "" # core API group
        resources: ["configmaps"]
    # This rule only applies to resources in the "kube-system" namespace.
    # The empty string "" can be used to select non-namespaced resources.
    namespaces: ["kube-system"]

  # Log node changes at RequestResponse level
  - level: None
    resources:
      - group: ""
        resources: ["nodes"]

  # Don't log watch requests by the "system:kube-proxy" on endpoints or services
  - level: None
    users: ["system:kube-proxy"]
    verbs: ["watch"]
    resources:
      - group: "" # core API group
        resources: ["endpoints", "services"]

  # Don't log authenticated requests to certain non-resource URL paths.
  - level: None
    userGroups: ["system:authenticated"]
    nonResourceURLs:
      - "/api*" # Wildcard matching.
      - "/version"
