apiVersion: audit.k8s.io/v1
kind: Policy
# Don't generate audit events for all requests in RequestReceived stage.
omitStages:
  - "RequestReceived"
  - "ResponseStarted"
  - "Panic"
rules:
  # Log pod changes at RequestResponse level
  - level: RequestResponse
    verbs: ["get", "list", "create", "delete"]
    resources:
      - group: "" # core API group
        resources: ["pods"]

  # Log Node view at RequestResponse level
  - level: RequestResponse
    verbs: ["get", "list"]
    resources:
      - group: "" # Core API group
        resources: ["nodes"]

  # Log service changes at RequestResponse level
  - level: RequestResponse
    verbs: ["get", "list", "create", "delete"]
    resources:
      - group: ""
        resources: ["services"]

  # Log configmap and secret changes at the Metadata level.
  - level: Metadata
    verbs: ["get", "list", "create", "delete"]
    resources:
      - group: ""
        resources: ["secrets", "configmaps"]

  # Log role and rolebinding changes at RequestResponse level
  - level: RequestResponse
    verbs: ["get", "list", "create", "delete"]
    resources:
      - group: "rbac.authorization.k8s.io"
        resources:
          ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]

  # Log serviceaccount changes at RequestResponse level
  - level: RequestResponse
    verbs: ["get", "list", "create", "delete"]
    resources:
      - group: ""
        resources: ["serviceaccounts"]

  # Log namespace changes at Metadata level
  - level: Metadata
    resources:
      - group: ""
        resources: ["namespaces"]

  # Log NetworkPolicy changes at RequestResponse level
  - level: RequestResponse
    verbs: ["get", "list", "create", "delete"]
    resources:
      - group: "networking.k8s.io"
        resources: ["networkpolicies"]
    namespaces: ["dev"]

  ### DON'T WATCH RULES

  # Log the request body of configmap changes in kube-system.
  - level: None
    resources:
      - group: ""
        resources: ["configmaps"]
    # This rule only applies to resources in the "kube-system" namespace.
    # The empty string "" can be used to select non-namespaced resources.
    namespaces: ["kube-system"]

  # Log node changes at RequestResponse level
  - level: None
    resources:
      - group: ""
        resources: ["nodes"]

  # Don't log watch requests by the "system:kube-proxy" on endpoints or services
  - level: None
    users: ["system:kube-proxy"]
    verbs: ["watch"]
    resources:
      - group: ""
        resources: ["endpoints", "services"]

  # Don't log authenticated requests to certain non-resource URL paths.
  - level: None
    userGroups: ["system:authenticated"]
    nonResourceURLs:
      - "/api*" # Wildcard matching.
      - "/version"
