apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: dev
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 4430
      targetPort: 4430
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: dev
data:
  nginx.conf: |
    server {
      listen       4430 ssl;
      server_name  localhost;

      ssl_certificate /etc/secret/tls.crt;
      ssl_certificate_key /etc/secret/tls.key;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: dev
  labels:
    app: nginx
spec:
  serviceAccountName: default
  automountServiceAccountToken: false
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: nginx
      image: nginx:dev_unprivileged
      ports:
        - containerPort: 4430
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        runAsNonRoot: true
        privileged: false
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "100Mi"
          cpu: "450m"
      volumeMounts:
        - name: cache-nginx
          mountPath: /var/cache/nginx
        - name: var-run
          mountPath: /var/run
        - name: tmp
          mountPath: /tmp
        - name: config-volume
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: secret-volume
          mountPath: /etc/secret
          readOnly: true
  volumes:
    - name: config-volume
      configMap:
        name: nginx-cm
    - name: secret-volume
      secret:
        secretName: nginx-secret
    - name: cache-nginx
      emptyDir: {}
    - name: var-run
      emptyDir: {}
    - name: tmp
      emptyDir: {}
