# NodePort for testing only
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: mt-development
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: mt-development
data:
  nginx.conf: |
    server {
      listen       443 ssl;
      server_name  localhost;

      ssl_certificate /etc/secret/nginx.crt;
      ssl_certificate_key /etc/secret/nginx.key;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: mt-development
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.25.5
      volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d
        - name: secret-volume
          mountPath: /etc/secret
      ports:
        - containerPort: 443
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  volumes:
    - name: config-volume
      configMap:
        name: nginx-cm
    - name: secret-volume
      secret:
        secretName: nginx-secret # Secret object created with kubectl (check /scripts/setup.sh)
