apiVersion: v1
kind: Pod
metadata:
  name: alpine-dev
  namespace: dev
  labels:
    app: alpine-dev
spec:
  containers:
    - name: alpine-dev
      image: alpine:dev
      # command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
      command:
        [
          "/bin/sh",
          "-c",
          "while true; do curl --cacert /etc/secret/tls.crt https://nginx-svc.dev.svc.cluster.local:443; sleep 15; done",
        ]
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret
  volumes:
    - name: secret-volume
      secret:
        secretName: nginx-secret
        items:
          - key: tls.crt
            path: tls.crt
