apiVersion: v1
kind: Pod
metadata:
  name: alpine-dev
  namespace: dev
  labels:
    app: alpine-dev
spec:
  containers:
    - name: alpine-dev
      image: alpine:dev
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
