apiVersion: v1
kind: Pod
metadata:
  name: alpine-dev
  namespace: dev
  labels:
    app: alpine-dev
spec:
  containers:
    - name: alpine-dev
      image: alpine:dev
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret
  volumes:
    - name: secret-volume
      secret:
        secretName: nginx-secret
        items:
          - key: tls.crt
            path: tls.crt
