apiVersion: v1
kind: Service
metadata:
  name: vuln-app-svc
  namespace: dev
spec:
  selector:
    app: vuln-app
  ports:
    - protocol: TCP
      port: 6000
      nodePort: 30007
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: vuln-app
  namespace: dev
  labels:
    app: vuln-app
spec:
  containers:
    - name: vuln-app
      image: vuln_app:1.0
      ports:
        - containerPort: 6000
