apiVersion: v1
kind: Service
metadata:
  name: vuln-app-svc-nodeport
  namespace: dev
spec:
  selector:
    app: vuln-app
  ports:
    - protocol: TCP
      port: 6000
      nodePort: 30007
  type: NodePort
